{{- $pgHost := include "unifi-os.postgresHost" . | trim -}}
{{- if $pgHost }}
{{- $rootCtx := . }}
{{- $pgPort := include "unifi-os.postgresPort" . }}
{{- $pgPassword := include "unifi-os.postgresPassword" . }}
{{- $configOverrideServices := (index (index .Values "unifi") "configOverrides" "services") | default list }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-unifi-core-override
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "unifi-os.standardLabels" . | nindent 4 }}
type: Opaque
stringData:
  local.yaml: |
    postgres:
      host: {{ $pgHost }}
      port: {{ $pgPort }}
      database: {{ include "unifi-os.postgresDatabase" . }}
      user: {{ include "unifi-os.postgresUser" . }}
      password: {{ $pgPassword | quote }}
{{- range $entry := $configOverrideServices }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $entry.dbSecretName }}
  namespace: {{ $rootCtx.Release.Namespace }}
  labels:
{{- include "unifi-os.standardLabels" $rootCtx | nindent 4 }}
type: Opaque
stringData:
  config.props: |
    db.name = {{ $entry.dbName }}
    db.host = {{ $pgHost }}
    db.port = {{ $pgPort }}
    db.encrypted = false
    db.username = {{ $entry.dbUser }}
    db.password = {{ $pgPassword }}
{{- end }}
{{- range $i, $username := (list "unifi-core" "ulp-go" "uid" "unifi-credential-server" "unifi-directory" "ucs-agent" "ucs-update" "unifi-identity-update") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: pg-login-{{ $username }}
  namespace: {{ $rootCtx.Release.Namespace }}
  labels:
{{- include "unifi-os.standardLabels" $rootCtx | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: "{{ $username }}"
  password: "{{ $pgPassword }}"
{{- end }}
{{- end }}
