{{- if not (include "unifi-os.rabbitmqUseExistingSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unifi-os.labels" (dict "root" . "component" "") | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  password: {{ include "unifi-os.rabbitmqPassword" . | quote }}
  erlang-cookie: {{ include "unifi-os.rabbitmqErlangCookie" . | quote }}
{{- end }}
{{- if not (include "unifi-os.postgresUseExistingSecret" .) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: unifi-pg-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unifi-os.labels" (dict "root" . "component" "") | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/basic-auth
stringData:
  username: unifi-core
  password: {{ include "unifi-os.postgresPassword" . | quote }}
{{- end }}
{{- if and .Values.backup.enabled (not .Values.backup.existingSecret.name) }}
---
# Backup credentials — created only when backup.existingSecret.name is not set.
apiVersion: v1
kind: Secret
metadata:
  name: unifi-backup-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unifi-os.labels" (dict "root" . "component" "") | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  password: {{ .Values.backup.password | quote }}
  storageUrl: {{ .Values.backup.storageUrl | quote }}
{{- end }}
{{- if and .Values.unifiExporter.enabled (not .Values.unifiExporter.existingSecret.name) }}
---
# Exporter credentials — created only when unifiExporter.existingSecret.name is not set.
apiVersion: v1
kind: Secret
metadata:
  name: unifi-exporter-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unifi-os.labels" (dict "root" . "component" "") | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  password: {{ .Values.unifiExporter.config.password | quote }}
  api-key: {{ .Values.unifiExporter.config.apiKey | quote }}
{{- end }}
