apiVersion: v2
name: unifi-os
description: >-
  UniFi OS Server - self-hosted UniFi management platform
type: application
version: 0.9.2
appVersion: "5.1.40"
dependencies:
  # RabbitMQ via CloudPirates chart.
  - name: rabbitmq
    repository: oci://registry-1.docker.io/cloudpirates
    version: "0.17.1"
    condition: rabbitmq.enabled

  - name: cluster
    repository: https://cloudnative-pg.github.io/charts
    version: "0.4.0"
    alias: postgres
    condition: postgres.enabled
